---
driver_plugin: vagrant
driver:
  network:
  - ["private_network", {ip: "192.168.134.20"}]
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: centos-6.4
  run_list:
  - recipe[yum-epel]

suites:
- name: default
  run_list: ["recipe[dhcp-test]"]
  attributes: {}
